version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: postgres-saas
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2466
      POSTGRES_DB: todos_db
    ports:
      - "5432:5432"
    networks:
      - saas-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend-saas
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - saas-network

networks:
  saas-network:

volumes:
  postgres_data:

